services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "50051:50051"
    networks:
      - zenith-network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    restart: on-failure
    env_file:
      - .env
    command: >
      sh -c "
        until nc -z db 5432;
        do
          echo 'Waiting for database to be ready...';
          sleep 2;
        done;
        echo 'Database is ready!';
        ./zenith-server"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    networks:
      - zenith-network
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=50051
    stdin_open: true
    tty: true

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - zenith-network

volumes:
  pgdata:

networks:
  zenith-network:
    driver: bridge