FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o zenith-client ./client/client.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/zenith-client .
COPY --from=builder /app/.env .

ENTRYPOINT [ "./zenith-client" ]