FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o zenith-server ./main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/zenith-server .
COPY --from=builder /app/.env .

EXPOSE 50051

CMD [ "./zenith-server" ]